scan_pro_robot:

  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125  
  
  arm_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
      # constraints:
        # goal_time: 0.6
        # stopped_velocity_tolerance: 0.05
        # hip: {trajectory: 0.1, goal: 0.1}
        # shoulder: {trajectory: 0.1, goal: 0.1}
        # elbow: {trajectory: 0.1, goal: 0.1}
        # wrist: {trajectory: 0.1, goal: 0.1}
      # stop_trajectory_duration: 0.5
      # state_publish_rate:  25
      # action_monitor_rate: 10
  # /scan_pro_robot/gazebo_ros_control:
  #     pid_gains:
  #       joint_1: {p: 1000.0, i: 100.0, d: 10.0}
  #       joint_2: {p: 1000.0, i: 100.0, d: 10.0}
  #       joint_3: {p: 1000.0, i: 100.0, d: 10.0}
  #       joint_4: {p: 1000.0, i: 100.0, d: 10.0}
  #       joint_5: {p: 1000.0, i: 100.0, d: 10.0}
  #       joint_6: {p: 100.0, i: 0.0, d: 0.0}
